### ISSUE TITLE
[Feature] Add OpenWebUI / similar chat interface

### ISSUE THREAD

**Issue by surajssd** [llm-d/llm-d#110]
Add an OpenWebUI deployment / similar chat interface to quickly use the models deployed using llm-d.

**Comment by yossiovadia** [comment]
tip, you'll need to create a NodePort service to expose the LLM-D gateway externally.

**Comment by frzifus** [comment]
Wouldnt it make sense modify to extend the helmchart to deploy and configure a OpenWebUI instance for testing instead of adding a nodePort option?

If its a test setup, you then can use `kubectl port-forward` to access OpenWebUi for testing.

Something like this:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui
spec:
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      containers:
        - name: open-webui
          image: ghcr.io/open-webui/open-webui:v0.6.15
          ports:
            - containerPort: 8080
          env:
            - name: OPENAI_API_BASE_URL
              value: "http://your-llmd-gateway:8080/v1"
```
